
pipeline{
  agent any

  environment {
    BRANCH_NAME = "${GIT_BRANCH}"
    SHORT_COMMIT = GIT_COMMIT.substring(0,7)
    BUILD_VERSION = "${GIT_COMMIT}"
  }

  stages {
    stage('Build') {
      steps {
        echo "=> Build Version: $BUILD_VERSION"
        echo "==> Build Service for branch: ${env.BRANCH_NAME}"
        sh "chmod +x -R ${env.WORKSPACE}"
        sh "jenkins/karros/build.sh"
        perfReport filterRegex: '', relativeFailedThresholdNegative: 1.2, relativeFailedThresholdPositive: 1.89, relativeUnstableThresholdNegative: 1.8, relativeUnstableThresholdPositive: 1.5, sourceDataFiles: 'out/geocode.jtl'
      }
    }
  }
  post {
    success {
      echo "==> Build Success"
    }
    failure {
      echo "==> Build Failure"
    }
  }
}
